### ISSUE TITLE
Issue Title: Implement Rate Limiting Middleware

### ISSUE THREAD

**Issue by Adesoji1** [AdrianPayne/fastapi-rocket-boilerplate#10]
Issue Description: Currently, the FastAPI Rocket Boilerplate lacks rate limiting middleware, which is essential for controlling the number of requests a client can make to the API within a specific time frame. This issue aims to implement rate limiting middleware, allowing developers to configure and enforce rate limits on API endpoints.

Proposed Solution: Implement a rate limiting middleware that:

Supports rate limits based on IP address or user tokens.
Allows developers to configure rate limits for specific routes or groups of routes.
Provides clear documentation on how to configure and use rate limiting in the boilerplate.
Expected Impact: The addition of rate limiting middleware would enhance the security and reliability of the API by preventing abuse and ensuring fair usage of resources

**Comment by AdrianPayne** [comment]
Hello Adesoji,

The nocache middleware is a middleware oriented to avoid the cache in the swagger documentation (a common situation working with Fastapi).
Therefore, the enhancement of this issue is not needed now.

Thanks so much for your time and effort on this, please keep using the project and supporting like this!
